# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  vmImage: ubuntu-latest



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: OcConditionalCmd@3
  displayName: Create Project if Not exists
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Connection'
    cmd: 'oc new-project azure-demo'
    condition: 'not_exists'
    resource: 'azure-demo'